easy_admin:
   entities:
    # List the entity class name you want to manage
    Category:
      class: App\Entity\Category
      new:
        fields: ['name', 'description']
    Post:
      class: App\Entity\Post
      list:
        fields: ['id', 'title', 'content', 'category']
      new:
        fields: ['title', 'content', 'category']
